name: "Destroy Okteto Pipeline"
description: "Destroy an Okteto Pipeline"
inputs:
  name: 
    description: 'The name of the pipeline'
    required: true
  namespace: 
    description: 'If present, the namespace scope for this action. If not specified, it will use the current context'
    required: false
  log-level:
    description: "Log level string. Valid options are debug, info, warn, error"
    required: false
  destroy-volumes:
    description: "Set to true to destroy the persistent volumes created by the development environment"
    required: false
    default: 'false'
  dependencies:
    description: "Force destroy of repositories in the 'dependencies' section"
    required: false
  timeout:
    description: "Timeout duration in Golang format (e.g., '5m' for 5 minutes, '1h' for 1 hour)"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.log-level }}
    - ${{ inputs.destroy-volumes }}
    - ${{ inputs.dependencies }}
    - ${{ inputs.timeout }}
branding:
  color: 'green'
  icon: 'settings'
